application: impostoespecial
version: 2-0
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/money.png
  upload: static/money.png
       
- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: scripts

- url: /.*
  script: impostoespecial.py
  